/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-29 02:43:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.wepet.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_header_link2.jsp", Long.valueOf(1678934352000L));
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_searchbar_link.jsp", Long.valueOf(1678934352000L));
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_header_link.jsp", Long.valueOf(1678934352000L));
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_navbar_link.jsp", Long.valueOf(1678934352000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- beautify ignore:start -->\r\n");
      out.write("<html lang=\"en\" class=\"light-style layout-menu-fixed\" dir=\"ltr\"\r\n");
      out.write("	data-theme=\"theme-default\" data-assets-path=\"resources/sneat/assets/\"\r\n");
      out.write("	data-template=\"vertical-menu-template-free\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("<title>관리자-수수료 페이지</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"resources/sneat/assets/img/favicon/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- Icons. Uncomment required icon fonts -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/fonts/boxicons.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Core CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/css/core.css\" class=\"template-customizer-core-css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/css/theme-default.css\" class=\"template-customizer-theme-css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/css/demo.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendors CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/libs/apex-charts/apex-charts.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Page CSS -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Helpers -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/js/helpers.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->\r\n");
      out.write("    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/js/config.js\"></script>");
      out.write("\r\n");
      out.write("  <!-- Vue.js ver2 -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/Pager.js\"></script>	\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"layout-wrapper layout-content-navbar\">\r\n");
      out.write("      <div class=\"layout-container\">\r\n");
      out.write("	<!-- navbar  -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!-- Layout wrapper -->\r\n");
      out.write("    <div class=\"layout-wrapper layout-content-navbar\">\r\n");
      out.write("      <div class=\"layout-container\">\r\n");
      out.write("        <!-- Menu -->\r\n");
      out.write("\r\n");
      out.write("        <aside id=\"layout-menu\" class=\"layout-menu menu-vertical menu bg-menu-theme\">\r\n");
      out.write("          <div class=\"app-brand demo\">\r\n");
      out.write("            <a href=\"/admin/main\" class=\"app-brand-link\">\r\n");
      out.write("			<!-- 로고..? -->\r\n");
      out.write("              <span class=\"app-brand-text demo menu-text fw-bolder ms-2\">Wepet</span>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none\">\r\n");
      out.write("              <i class=\"bx bx-chevron-left bx-sm align-middle\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"menu-inner-shadow\"></div>\r\n");
      out.write("\r\n");
      out.write("          <ul class=\"menu-inner py-1\">\r\n");
      out.write("            <!-- Dashboard -->\r\n");
      out.write("            <li class=\"menu-item active\">\r\n");
      out.write("              <a href=\"/admin/main\" class=\"menu-link\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-home-circle\"></i>\r\n");
      out.write("                <div data-i18n=\"Analytics\">main</div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Layouts -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Components -->\r\n");
      out.write("            <li class=\"menu-header small text-uppercase\"><span class=\"menu-header-text\">고객관리</span></li>\r\n");
      out.write("	\r\n");
      out.write("	             <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"tables-basic.html\" class=\"menu-link\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("                <div data-i18n=\"Tables\">이용고객조회</div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <!-- 고객 / 펫시터  -->\r\n");
      out.write("                    <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("                <div data-i18n=\"Account Settings\">팻시터관리</div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"menu-sub\">\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-account.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Account\">펫시터 조회</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Notifications\">펫시터 승인내역 </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 게시글관리 -->\r\n");
      out.write("                     <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-collection\"></i>\r\n");
      out.write("                <div data-i18n=\"Account Settings\">게시글관리</div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"menu-sub\">\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-account.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Account\">커뮤니티 게시판</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Notifications\">고객센터 게시판 </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               \r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Misc -->\r\n");
      out.write("            <li class=\"menu-header small text-uppercase\"><span class=\"menu-header-text\">결제</span></li>\r\n");
      out.write("                   <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("                <div data-i18n=\"Account Settings\">결제 관리</div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"menu-sub\">\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-account.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Account\">결제내역 관리</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Notifications\">정산내역 관리</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("               \r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- / Menu -->");
      out.write("\r\n");
      out.write("	<!-- navbar end -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Layout container -->\r\n");
      out.write("	<div class=\"layout-page\">\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 상단, 서치바 -->\r\n");
      out.write("		");
      out.write(" \r\n");
      out.write(" <nav\r\n");
      out.write("            class=\"layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme\"\r\n");
      out.write("            id=\"layout-navbar\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none\">\r\n");
      out.write("              <a class=\"nav-item nav-link px-0 me-xl-4\" href=\"javascript:void(0)\">\r\n");
      out.write("                <i class=\"bx bx-menu bx-sm\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-nav-right d-flex align-items-center\" id=\"navbar-collapse\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("              <ul class=\"navbar-nav flex-row align-items-center ms-auto\">\r\n");
      out.write("              \r\n");
      out.write("                <!-- Place this tag where you want the button to render. -->\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item lh-1 me-3\">\r\n");
      out.write("                <!-- 우리 사이트 홈페이지로 이동할 수 있게 해주기...  현재는 어드민 페이지 메인 연결...-->\r\n");
      out.write("                  <a href=\"/admin/main\">Wepet site</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!-- User -->\r\n");
      out.write("                <li class=\"nav-item navbar-dropdown dropdown-user dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle hide-arrow\" href=\"javascript:void(0);\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                    <div class=\"avatar avatar-online\">\r\n");
      out.write("                      <img src=\"/resources/sneat/assets/img/avatars/admin1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                        <div class=\"d-flex\">\r\n");
      out.write("                          <div class=\"flex-shrink-0 me-3\">\r\n");
      out.write("                            <div class=\"avatar avatar-online\">\r\n");
      out.write("                              <img src=\"/resources/sneat/assets/img/avatars/admin1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"flex-grow-1\">\r\n");
      out.write("                            <span class=\"fw-semibold d-block\">wepet admin</span>\r\n");
      out.write("                            <small class=\"text-muted\">company root</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write(" \r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"/admin/loginform\">\r\n");
      out.write("                        <i class=\"bx bx-power-off me-2\"></i>\r\n");
      out.write("                        <span class=\"align-middle\">Log Out</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!--/ User -->\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("\r\n");
      out.write("          <!-- / Navbar -->");
      out.write("\r\n");
      out.write("		<!-- 서치바 End -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Content wrapper -->\r\n");
      out.write("          <div class=\"content-wrapper\">\r\n");
      out.write("            <!-- Content -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container-xxl flex-grow-1 container-p-y\">\r\n");
      out.write("              <h4 class=\"fw-bold py-3 mb-4\"><span class=\"text-muted fw-light\">관리자 페이지/</span> 펫시터 수수료 지급 관리</h4>\r\n");
      out.write("\r\n");
      out.write("              <!-- Basic Layout & Basic with Icons -->\r\n");
      out.write("              <div class=\"row\"  id=\"app1\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Basic with Icons -->\r\n");
      out.write("                <div class=\"col-xxl\">\r\n");
      out.write("                  <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-header d-flex align-items-center justify-content-between\">\r\n");
      out.write("                      <h5 class=\"mb-0\">지급 수수료 펫시터 리스트</h5>\r\n");
      out.write("                      <small class=\"text-muted float-end\">매월 15일 일괄 지급</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <form>\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-4\">\r\n");
      out.write("				                <h5 class=\"card-header\">2023년 3월</h5>							\r\n");
      out.write("							</div>\r\n");
      out.write("                            <div class=\"col-sm-3\">\r\n");
      out.write("                               <div class=\"form-floating\">\r\n");
      out.write("                                   <select class=\"form-control  border-1 bg-light text-center\" name=\"dropDown1\" id=\"dropDown1\" onchange=\"ChangeSecondDropContent(this, 'dropDown2');\">\r\n");
      out.write("								        <option value=\"0\" selected>조회</option> \r\n");
      out.write("								        <option value=\"1\">건당 조회</option> \r\n");
      out.write("								        <option value=\"2\">펫시터별 조회</option> \r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("                            <div class=\"col-sm-3\">\r\n");
      out.write("                               <div class=\"form-floating\">\r\n");
      out.write("                                    <select class=\"form-control  border-1 bg-light text-center\" name=\"dropDown2\" id=\"dropDown2\">\r\n");
      out.write("								        <option value=\"3\" selected>상위 선택지를 먼저 선택해주세요</option> \r\n");
      out.write("								        <option value=\"4\"></option> \r\n");
      out.write("								        <option value=\"5\"></option> \r\n");
      out.write("								        <option value=\"6\"></option> \r\n");
      out.write("								        <option value=\"7\"></option> \r\n");
      out.write("									</select> \r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("                            <div class=\"col-sm-2 text-center\">\r\n");
      out.write("                               <div class=\"form-floating\">\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-outline-primary\" id=\"bt_select\">조회하기</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("			                <div class=\"table-responsive text-nowrap\">\r\n");
      out.write("			                  <table class=\"table table-hover\">\r\n");
      out.write("			                    <thead class=\"table-active text-center\">\r\n");
      out.write("			                      <tr>\r\n");
      out.write("			                        <th>선택</th>\r\n");
      out.write("			                        <th>펫시터 이름</th>\r\n");
      out.write("			                        <th>총 수익</th>\r\n");
      out.write("			                        <th>수수료 계산</th>\r\n");
      out.write("			                        <th>지급되어야할 총 수수료</th>\r\n");
      out.write("			                        <th>지급된 총 수수료</th>\r\n");
      out.write("			                        <th>정산 상태</th>\r\n");
      out.write("			                        <th>개별관리</th>\r\n");
      out.write("			                      </tr>\r\n");
      out.write("			                    </thead>\r\n");
      out.write("			                    <tbody class=\"table-border-bottom-0 text-center\">\r\n");
      out.write("			                    \r\n");
      out.write("									<template v-for=\"(review, i) in currentList\">\r\n");
      out.write("										<product :key=\"review\" :obj=\"review\" :num=\"num-i\"/>				                  	\r\n");
      out.write("				                  	</template>\r\n");
      out.write("				                  	<tr>\r\n");
      out.write("				                  		<td class=\"text-center\" colspan=\"8\" id=\"paging-area\"></td>\r\n");
      out.write("				                  	</tr>\r\n");
      out.write("									\r\n");
      out.write("			                    </tbody>\r\n");
      out.write("			                  </table>\r\n");
      out.write("			                </div>\r\n");
      out.write("			              </div>\r\n");
      out.write("                        <div class=\"row justify-content-end mt-3\">\r\n");
      out.write("                          <div class=\"col text-end\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary\" id=\"bt_all\">선택 일괄 정산</button>\r\n");
      out.write("                          </div>                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                      </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- / Content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content-backdrop fade\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- / Layout page -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Overlay -->\r\n");
      out.write("	<div class=\"layout-overlay layout-menu-toggle\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- / Layout wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- head_link 2 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Core JS -->\r\n");
      out.write("    <!-- build:js assets/vendor/js/core.js -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/jquery/jquery.js\"></script>\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/popper/popper.js\"></script>\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/js/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/js/menu.js\"></script>\r\n");
      out.write("    <!-- endbuild -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendors JS -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/apex-charts/apexcharts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main JS -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page JS -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/js/dashboards-analytics.js\"></script>");
      out.write("\r\n");
      out.write("	<!-- head_link 2  End -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("let pager=new Pager(); //인스턴스 생성\r\n");
      out.write("let currentPage=1; //비동기로 새로고침 안되려면 js의 전역변수로 나와있어야함\r\n");
      out.write("\r\n");
      out.write("let app1;\r\n");
      out.write("let key=0;\r\n");
      out.write("\r\n");
      out.write("var category = new Array ();\r\n");
      out.write("category['건당 조회'] = ['전체 리스트', '정산 완료 리스트', '정산 미완료 리스트'];\r\n");
      out.write("category['펫시터별 조회'] = ['펫시터별 수익 합계 조회', '정산 완료 금액 합계 조회', '정산 미완료 금액 합계 조회'];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("const product={\r\n");
      out.write("	template:`    	\r\n");
      out.write("        <tr>\r\n");
      out.write("	      	<td><input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"defaultCheck1\" name=\"defaultCheck1\" v-on:click=\"\"></td>\r\n");
      out.write("	        <td><i class=\"fab fa-angular fa-lg text-danger me-3\"><strong>{{json.petSitter.sitter_nickname}}</strong></i></td>                        \r\n");
      out.write("	        <td>{{json.earnings}} 원</td>\r\n");
      out.write("	        <td>{{json.earnings}} x 10</td>                        \r\n");
      out.write("	        <td>{{json.earnings*0.1}} 원</td>        \r\n");
      out.write("	        <td>{{json.gottenfee}} 원</td>                        \r\n");
      out.write("            <td v-if=\"json.status+'==0'\">{{(json.earnings*0.1)-json.gottenfee}} 원 정산 미완료</td>\r\n");
      out.write("        	<td v-else>정산 완료</td>        \r\n");
      out.write("	        <td><button type=\"button\" class=\"btn btn-outline-primary\" id=\"bt_caseby\" v-on:click=\"givefee(json)\">개별 지급</button></td>                        \r\n");
      out.write("      </tr>\r\n");
      out.write("	`,\r\n");
      out.write("	props:['obj', 'num'], \r\n");
      out.write("	data(){ \r\n");
      out.write("		return{\r\n");
      out.write("			json:this.obj,\r\n");
      out.write("			n:this.num\r\n");
      out.write("		};\r\n");
      out.write("	},\r\n");
      out.write("	methods:{\r\n");
      out.write("		givefee:function(json){\r\n");
      out.write("			//console.log(this.json.sales_idx);\r\n");
      out.write("			let gottenfee=this.json.gottenfee;\r\n");
      out.write("			let getfee=(this.json.earnings*0.1)-json.gottenfee\r\n");
      out.write("			let sales_idx=this.json.sales_idx;\r\n");
      out.write("\r\n");
      out.write("			let allData = {\"gottenfee\": gottenfee, \"sales_idx\": sales_idx, \"getfee\": getfee };\r\n");
      out.write("			//console.log(allData);\r\n");
      out.write("			\r\n");
      out.write("			if(!confirm(\"총 \"+getfee+\"원 정산 하시겠습니까?\")){\r\n");
      out.write("				return; \r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"/admin/rest/giveFee\",\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				data: allData,\r\n");
      out.write("				success:function(result, status, xhr){\r\n");
      out.write("					console.log(result.msg);\r\n");
      out.write("\r\n");
      out.write("					getList();\r\n");
      out.write("					\r\n");
      out.write("				},\r\n");
      out.write("				error:function(xhr, status, err){\r\n");
      out.write("					console.log(\"에러에요\"+err);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	}	\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function init(){	\r\n");
      out.write("	app1=new Vue({\r\n");
      out.write("		el:\"#app1\",\r\n");
      out.write("		components:{\r\n");
      out.write("			product\r\n");
      out.write("		},\r\n");
      out.write("		data:{\r\n");
      out.write("			count:5,\r\n");
      out.write("			salesList:[], //전체 배열\r\n");
      out.write("			currentList:[], //페이지당 보여질 배열\r\n");
      out.write("			num:0 //페이지당 시작 번호를 뷰 컴포넌트에서 접근할 수 있도록\r\n");
      out.write("		}\r\n");
      out.write("	});			\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pageLink(n) {\r\n");
      out.write("	//서버에서 가져온 데이터를 대상으로 페이징 로직을 적용해보기\r\n");
      out.write("	pager.init(app1.salesList, n); //원하는페이지만 넘겨받자	\r\n");
      out.write("	\r\n");
      out.write("	//console.log(\"totalRecord =\" , pager.totalRecord);\r\n");
      out.write("	//console.log(\"pageSize =\" , pager.pageSize);\r\n");
      out.write("	//console.log(\"totalPage =\" , pager.totalPage);\r\n");
      out.write("	//console.log(\"blockSize =\" , pager.blockSize);\r\n");
      out.write("	//console.log(\"currentPage =\" , pager.currentPage);\r\n");
      out.write("	//console.log(\"firstPage =\" , pager.firstPage);\r\n");
      out.write("	//console.log(\"lastPage =\" , pager.lastPage);\r\n");
      out.write("	//console.log(\"curPos =\" , pager.curPos);\r\n");
      out.write("	//console.log(\"num =\" , pager.num);\r\n");
      out.write("	\r\n");
      out.write("	app1.num=pager.num;\r\n");
      out.write("\r\n");
      out.write("	app1.currentList.splice(0, app1.currentList.length); //싹 비우고 \r\n");
      out.write("	for(let i=pager.curPos; i<pager.curPos+pager.pageSize; i++){ //채워넣기\r\n");
      out.write("		\r\n");
      out.write("		if(pager.num<1)break;\r\n");
      out.write("		pager.num--;\r\n");
      out.write("		\r\n");
      out.write("		app1.currentList.push(app1.salesList[i]);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function paging() {\r\n");
      out.write("	//넘버링 출력\r\n");
      out.write("	$(\"#paging-area *\").remove();\r\n");
      out.write("	for(let i=pager.firstPage; i<pager.lastPage; i++){\r\n");
      out.write("		if(i>pager.totalPage)break; \r\n");
      out.write("		$(\"#paging-area\").append(\"<a href='javascript:pageLink(\"+i+\")' style='margin:3px'>\"+i+\"</a>\");\r\n");
      out.write("	}       	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getList() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"/admin/rest/fee\",\r\n");
      out.write("		type:\"get\",\r\n");
      out.write("		success:function(result, status, xhr){\r\n");
      out.write("			app1.salesList=result;\r\n");
      out.write("			//console.log(result);			\r\n");
      out.write("			\r\n");
      out.write("			pageLink(currentPage); \r\n");
      out.write("			\r\n");
      out.write("			paging();\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}	\r\n");
      out.write("\r\n");
      out.write("function ChangeSecondDropContent (select1, select2) { \r\n");
      out.write("\r\n");
      out.write("    var topCate = select1.options[select1.selectedIndex].text;\r\n");
      out.write("    var select2 = document.getElementById (select2);\r\n");
      out.write("\r\n");
      out.write("    // removes all options from select 2\r\n");
      out.write("    while (select2.options.length) {\r\n");
      out.write("        select2.options.remove (0);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // adds new options to select 2\r\n");
      out.write("    var subArray = category[topCate];\r\n");
      out.write("\r\n");
      out.write("    if (subArray) {\r\n");
      out.write("        for (var i=0; i < subArray.length; i++) {\r\n");
      out.write("            var option = new Option (subArray[i], i);\r\n");
      out.write("            select2.options.add (option);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("function selectedList() {\r\n");
      out.write("	let val1=$(\"#dropDown1 option:selected\").val();\r\n");
      out.write("	let val2=$(\"#dropDown2 option:selected\").val();\r\n");
      out.write("\r\n");
      out.write("	let allData = { \"val1\": val1, \"val2\": val2 };\r\n");
      out.write("	let path=null;\r\n");
      out.write("	let type=null;\r\n");
      out.write("	\r\n");
      out.write("	if(val1==1 && val2==0){\r\n");
      out.write("		path=\"/admin/rest/fee\";\r\n");
      out.write("		type=\"get\";\r\n");
      out.write("	}else if(val1==2 && val2==0){\r\n");
      out.write("		path=\"/admin/rest/feeSum\";\r\n");
      out.write("		type=\"get\"\r\n");
      out.write("	}else{\r\n");
      out.write("		path=\"/admin/rest/feeList\";\r\n");
      out.write("		type=\"post\"\r\n");
      out.write("	}\r\n");
      out.write("	//console.log(\"경로\",path);\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:path,\r\n");
      out.write("		type:type,\r\n");
      out.write("		data:allData,\r\n");
      out.write("		success:function(result, status, xhr){\r\n");
      out.write("			app1.salesList=result;\r\n");
      out.write("//			console.log(result);			\r\n");
      out.write("			\r\n");
      out.write("			pageLink(currentPage); \r\n");
      out.write("			paging();\r\n");
      out.write("				\r\n");
      out.write("		}\r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function giveselected() {\r\n");
      out.write("	let a=$('input:checkbox[id=\"defaultCheck1\"]').is(\":checked\") == true\r\n");
      out.write("	\r\n");
      out.write("	$('input:checkbox[name=\"defaultCheck1\"]').each(function() {\r\n");
      out.write("\r\n");
      out.write("//	      this.checked = true; //checked 처리\r\n");
      out.write("\r\n");
      out.write("	      if(this.checked){//checked 처리된 항목의 값\r\n");
      out.write("\r\n");
      out.write("	            alert(this.index); \r\n");
      out.write("\r\n");
      out.write("	      }\r\n");
      out.write("\r\n");
      out.write("	 });\r\n");
      out.write("	\r\n");
      out.write("	//console.log(a);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){	\r\n");
      out.write("	init();		\r\n");
      out.write("	getList();\r\n");
      out.write("	\r\n");
      out.write("	$(\"#bt_select\").click(function(){\r\n");
      out.write("		selectedList();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#bt_all\").click(function(){\r\n");
      out.write("		giveselected();\r\n");
      out.write("	});\r\n");
      out.write("			\r\n");
      out.write("});	\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
