/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-04-01 04:54:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.wepet.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.edu.wepet.domain.Holiday;
import java.util.List;

public final class sitter_005fcalendar_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_header_link2.jsp", Long.valueOf(1678934352000L));
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_searchbar_link.jsp", Long.valueOf(1678934352000L));
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_header_link.jsp", Long.valueOf(1678934352000L));
    _jspx_dependants.put("/WEB-INF/views/wepet/client/../../sneat/inc/sneat_navbar_link.jsp", Long.valueOf(1678934352000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.edu.wepet.domain.Holiday");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.slf4j.Logger");
    _jspx_imports_classes.add("org.slf4j.LoggerFactory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!-- beautify ignore:start -->\n");
      out.write("<html lang=\"en\" class=\"light-style layout-menu-fixed\" dir=\"ltr\" data-theme=\"theme-default\" data-assets-path=\"../assets/\" data-template=\"vertical-menu-template-free\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\" />\n");
      out.write("\n");
      out.write("<title>펫시터 메인 페이지</title>\n");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("\n");
      out.write("<!-- BootStrap -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("@import\n");
      out.write("	url('https://fonts.googleapis.com/css?family=Questrial&display=swap');\n");
      out.write("\n");
      out.write("#form1 {\n");
      out.write("	background-color: white;\n");
      out.write("	height: auto;\n");
      out.write("	width: 550px;\n");
      out.write("	margin: 0px;\n");
      out.write("	padding: 20px;\n");
      out.write("	margin: 0 auto;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	box-shadow: 0px 40px 30px -20px rgba(0, 0, 0, 0.3);\n");
      out.write("}\n");
      out.write("\n");
      out.write("td {\n");
      out.write("	width: 50px;\n");
      out.write("	height: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Calendar {\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Calendar>thead>tr:first-child>td {\n");
      out.write("	font-family: 'Questrial', sans-serif;\n");
      out.write("	font-size: 1.1em;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Calendar>thead>tr:last-child>td {\n");
      out.write("	font-family: 'Questrial', sans-serif;\n");
      out.write("	font-weight: 600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Calendar>tbody>tr>td>p {\n");
      out.write("	font-family: 'Montserrat', sans-serif;\n");
      out.write("	height: 45px;\n");
      out.write("	width: 45px;\n");
      out.write("	border-radius: 45px;\n");
      out.write("	transition-duration: .2s;\n");
      out.write("	line-height: 45px;\n");
      out.write("	margin: 2.5px;\n");
      out.write("	display: block;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pastDay {\n");
      out.write("	color: lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".futureDay, .today {\n");
      out.write("	background-color: #FFFFFF;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".futureDay:hover {\n");
      out.write("	background: #eee;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".futureDay.choiceDay {\n");
      out.write("	background: #1ac50d;\n");
      out.write("	color: #fff;\n");
      out.write("	font-weight: 600;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"resources/sneat/assets/img/favicon/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <!-- Icons. Uncomment required icon fonts -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/fonts/boxicons.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Core CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/css/core.css\" class=\"template-customizer-core-css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/css/theme-default.css\" class=\"template-customizer-theme-css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/css/demo.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendors CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/sneat/assets/vendor/libs/apex-charts/apex-charts.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Page CSS -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Helpers -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/js/helpers.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->\r\n");
      out.write("    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/js/config.js\"></script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<!-- navbar  -->\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!-- Layout wrapper -->\r\n");
      out.write("    <div class=\"layout-wrapper layout-content-navbar\">\r\n");
      out.write("      <div class=\"layout-container\">\r\n");
      out.write("        <!-- Menu -->\r\n");
      out.write("\r\n");
      out.write("        <aside id=\"layout-menu\" class=\"layout-menu menu-vertical menu bg-menu-theme\">\r\n");
      out.write("          <div class=\"app-brand demo\">\r\n");
      out.write("            <a href=\"/admin/main\" class=\"app-brand-link\">\r\n");
      out.write("			<!-- 로고..? -->\r\n");
      out.write("              <span class=\"app-brand-text demo menu-text fw-bolder ms-2\">Wepet</span>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none\">\r\n");
      out.write("              <i class=\"bx bx-chevron-left bx-sm align-middle\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"menu-inner-shadow\"></div>\r\n");
      out.write("\r\n");
      out.write("          <ul class=\"menu-inner py-1\">\r\n");
      out.write("            <!-- Dashboard -->\r\n");
      out.write("            <li class=\"menu-item active\">\r\n");
      out.write("              <a href=\"/admin/main\" class=\"menu-link\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-home-circle\"></i>\r\n");
      out.write("                <div data-i18n=\"Analytics\">main</div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Layouts -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Components -->\r\n");
      out.write("            <li class=\"menu-header small text-uppercase\"><span class=\"menu-header-text\">고객관리</span></li>\r\n");
      out.write("	\r\n");
      out.write("	             <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"tables-basic.html\" class=\"menu-link\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("                <div data-i18n=\"Tables\">이용고객조회</div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <!-- 고객 / 펫시터  -->\r\n");
      out.write("                    <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("                <div data-i18n=\"Account Settings\">팻시터관리</div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"menu-sub\">\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-account.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Account\">펫시터 조회</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Notifications\">펫시터 승인내역 </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 게시글관리 -->\r\n");
      out.write("                     <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-collection\"></i>\r\n");
      out.write("                <div data-i18n=\"Account Settings\">게시글관리</div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"menu-sub\">\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-account.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Account\">커뮤니티 게시판</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Notifications\">고객센터 게시판 </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               \r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Misc -->\r\n");
      out.write("            <li class=\"menu-header small text-uppercase\"><span class=\"menu-header-text\">결제</span></li>\r\n");
      out.write("                   <li class=\"menu-item\">\r\n");
      out.write("              <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("                <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("                <div data-i18n=\"Account Settings\">결제 관리</div>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"menu-sub\">\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-account.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Account\">결제내역 관리</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                    <div data-i18n=\"Notifications\">정산내역 관리</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("               \r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- / Menu -->");
      out.write("\n");
      out.write("	<!-- navbar end -->\n");
      out.write("\n");
      out.write("	<!-- Layout container -->\n");
      out.write("	<div class=\"layout-page\">\n");
      out.write("		<!-- Navbar -->\n");
      out.write("\n");
      out.write("		<!-- 상단, 서치바 -->\n");
      out.write("		");
      out.write(" \r\n");
      out.write(" <nav\r\n");
      out.write("            class=\"layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme\"\r\n");
      out.write("            id=\"layout-navbar\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none\">\r\n");
      out.write("              <a class=\"nav-item nav-link px-0 me-xl-4\" href=\"javascript:void(0)\">\r\n");
      out.write("                <i class=\"bx bx-menu bx-sm\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-nav-right d-flex align-items-center\" id=\"navbar-collapse\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("              <ul class=\"navbar-nav flex-row align-items-center ms-auto\">\r\n");
      out.write("              \r\n");
      out.write("                <!-- Place this tag where you want the button to render. -->\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item lh-1 me-3\">\r\n");
      out.write("                <!-- 우리 사이트 홈페이지로 이동할 수 있게 해주기...  현재는 어드민 페이지 메인 연결...-->\r\n");
      out.write("                  <a href=\"/admin/main\">Wepet site</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!-- User -->\r\n");
      out.write("                <li class=\"nav-item navbar-dropdown dropdown-user dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle hide-arrow\" href=\"javascript:void(0);\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                    <div class=\"avatar avatar-online\">\r\n");
      out.write("                      <img src=\"/resources/sneat/assets/img/avatars/admin1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                        <div class=\"d-flex\">\r\n");
      out.write("                          <div class=\"flex-shrink-0 me-3\">\r\n");
      out.write("                            <div class=\"avatar avatar-online\">\r\n");
      out.write("                              <img src=\"/resources/sneat/assets/img/avatars/admin1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"flex-grow-1\">\r\n");
      out.write("                            <span class=\"fw-semibold d-block\">wepet admin</span>\r\n");
      out.write("                            <small class=\"text-muted\">company root</small>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write(" \r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a class=\"dropdown-item\" href=\"/admin/loginform\">\r\n");
      out.write("                        <i class=\"bx bx-power-off me-2\"></i>\r\n");
      out.write("                        <span class=\"align-middle\">Log Out</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!--/ User -->\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("\r\n");
      out.write("          <!-- / Navbar -->");
      out.write("\n");
      out.write("		<!-- 서치바 End -->\n");
      out.write("\n");
      out.write("		<!-- Main -->\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"row\" style=\"margin-top: 150px\">\n");
      out.write("				<div class=\"col-lg-6\">\n");
      out.write("					<form id=\"form1\">\n");
      out.write("						<div>\n");
      out.write("							<table class=\"Calendar\" style=\"width: 500px; height: 500px\">\n");
      out.write("								<thead>\n");
      out.write("									<tr>\n");
      out.write("										<td onClick=\"prevCalendar();\" style=\"cursor: pointer;\">&#60;</td>\n");
      out.write("										<td colspan=\"5\"><span id=\"calYear\"></span>년 <span id=\"calMonth\"></span>월</td>\n");
      out.write("										<td onClick=\"nextCalendar();\" style=\"cursor: pointer;\">&#62;</td>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<td>일</td>\n");
      out.write("										<td>월</td>\n");
      out.write("										<td>화</td>\n");
      out.write("										<td>수</td>\n");
      out.write("										<td>목</td>\n");
      out.write("										<td>금</td>\n");
      out.write("										<td>토</td>\n");
      out.write("									</tr>\n");
      out.write("								</thead>\n");
      out.write("								<tbody>\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary btn-sm\" data-toggle=\"modal\" data-target=\"#calendarModal\">휴무등록</button>\n");
      out.write("								</tbody>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("				<div calss=\"col-lg-6\" style=\"width: 570px; height: 500px margin-left: 0px; background-color: white;\">\n");
      out.write("					<div style=\"text-align: center; margin-top: 5px\">\n");
      out.write("						<button class=\"btn btn-primary btn-lg\" type=\"button\" id=\"bt_live\">진행중인일정</button>\n");
      out.write("						<button class=\"btn btn-primary btn-lg\" type=\"button\" id=\"bt_today\">오늘의일정</button>\n");
      out.write("   						<button class=\"btn btn-primary btn-lg\" type=\"button\" id=\"bt_res\">예약일정</button>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-xl\" id=\"pet_live\" style=\"display: none;\">\n");
      out.write("						<div class=\"card mb-4\">\n");
      out.write("							<div class=\"card-header d-flex justify-content-between align-items-center\">\n");
      out.write("								<h5 class=\"mb-0\">진행중인 일정</h5>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"card-body\">\n");
      out.write("								<form>\n");
      out.write("									<div class=\"mb-3\">\n");
      out.write("										<label class=\"form-label\" for=\"basic-default-fullname\">예약일시</label> \n");
      out.write("										<input type=\"text\" class=\"form-control\" readonly=\"readonly\" id=\"basic-default-fullname\" placeholder=\"John Doe\">\n");
      out.write("									</div>\n");
      out.write("									<div class=\"mb-3\">\n");
      out.write("										<label class=\"form-label\" for=\"basic-default-company\">고객성명</label> \n");
      out.write("										<input type=\"text\" class=\"form-control\" readonly=\"readonly\" id=\"basic-default-company\" placeholder=\"ACME Inc.\">\n");
      out.write("									</div>\n");
      out.write("									<div class=\"mb-3\">\n");
      out.write("										<label class=\"form-label\" for=\"basic-default-phone\">펫 종류</label> \n");
      out.write("										<input type=\"text\" id=\"basic-default-phone\" readonly=\"readonly\" class=\"form-control phone-mask\" placeholder=\"고양이\">\n");
      out.write("									</div>\n");
      out.write("									<div class=\"mb-3\">\n");
      out.write("										<label class=\"form-label\" for=\"basic-default-message\">요청사항</label>\n");
      out.write("										<textarea id=\"basic-default-message\" readonly=\"readonly\" class=\"form-control\" placeholder=\"Hi, Do you have a moment to talk Joe?\">\n");
      out.write("										</textarea>\n");
      out.write("									</div>\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary\">일지작성</button>\n");
      out.write("								</form>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"col-xl\" id=\"pet_today\">\n");
      out.write("						<div class=\"card mb-4\">\n");
      out.write("							<div class=\"card-header d-flex justify-content-between align-items-center\">\n");
      out.write("								<h5 class=\"mb-0\">오늘의 일정</h5>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"card-body\">\n");
      out.write("								<form>\n");
      out.write("									<div class=\"mb-3\">\n");
      out.write("										<label class=\"form-label\" for=\"basic-default-fullname\">예약일시</label> \n");
      out.write("										<input type=\"text\" class=\"form-control\" readonly=\"readonly\" id=\"basic-default-fullname\" placeholder=\"John Doe\">\n");
      out.write("									</div>\n");
      out.write("									<div class=\"mb-3\">\n");
      out.write("										<label class=\"form-label\" for=\"basic-default-company\">주소</label> \n");
      out.write("										<input type=\"text\" class=\"form-control\" readonly=\"readonly\" id=\"basic-default-company\" placeholder=\"ACME Inc.\">\n");
      out.write("									</div>\n");
      out.write("									<div class=\"mb-3\">\n");
      out.write("										<label class=\"form-label\" for=\"basic-default-message\">요청사항</label>\n");
      out.write("										<textarea id=\"basic-default-message\" readonly=\"readonly\" class=\"form-control\" placeholder=\"Hi, Do you have a moment to talk Joe?\">\n");
      out.write("										</textarea>\n");
      out.write("									</div>\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary\" id=\"bt_go\">일정진행</button>\n");
      out.write("								</form>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"col-xxl\" id=\"pet_showlist\" style=\"display: none;\">\n");
      out.write("						<div class=\"card mb-4\">\n");
      out.write("							<div class=\"card-header d-flex align-items-center justify-content-between\">\n");
      out.write("								<h5 class=\"mb-0\">전체 예약 일정</h5>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"card-body\">\n");
      out.write("								<form>\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"table-responsive text-nowrap\">\n");
      out.write("											<table class=\"table table-hover\">\n");
      out.write("												<thead class=\"table-active text-center\">\n");
      out.write("													<tr>\n");
      out.write("														<th>No</th>\n");
      out.write("														<th>예약일</th>\n");
      out.write("														<th>견종</th>\n");
      out.write("														<th>펫의 수</th>\n");
      out.write("													</tr>\n");
      out.write("												</thead>\n");
      out.write("												<tbody class=\"table-border-bottom-0 text-center\">\n");
      out.write("													<tr> \n");
      out.write("														<td>01</td>\n");
      out.write("														<td>2023-03-28</td>\n");
      out.write("														<td>소형견</td>\n");
      out.write("														<td>2마리</td>\n");
      out.write("													</tr>\n");
      out.write("												</tbody>\n");
      out.write("											</table>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</form>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Modal start -->\n");
      out.write("		<div class=\"modal fade\" id=\"calendarModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\" id=\"exampleModalLabel\">휴무일을 설정하세요</h5>\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("							<span aria-hidden=\"true\">&times;</span>\n");
      out.write("						</button>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<input type=\"text\" value=\"휴무\" readonly class=\"form-control\" id=\"calendar_content\"> <label for=\"taskId\" class=\"col-form-label\">시작 날짜</label> <input type=\"date\" class=\"form-control\" id=\"calendar_start_date\"> <label for=\"taskId\" class=\"col-form-label\">종료 날짜</label> <input type=\"date\" class=\"form-control\" id=\"calendar_end_date\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-warning\" data-dismiss=\"modal\" id=\"addCalendar\">등록</button>\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\" id=\"sprintSettingModalClose\">취소</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- Modal end -->\n");
      out.write("\n");
      out.write("		<!-- 일지모달 start -->\n");
      out.write("		<div class=\"modal fade\" id=\"calendarModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\" id=\"exampleModalLabel\">휴무일을 설정하세요</h5>\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("							<span aria-hidden=\"true\">&times;</span>\n");
      out.write("						</button>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<input type=\"text\" value=\"휴무\" readonly class=\"form-control\" id=\"calendar_content\"> <label for=\"taskId\" class=\"col-form-label\">시작 날짜</label> <input type=\"date\" class=\"form-control\" id=\"calendar_start_date\"> <label for=\"taskId\" class=\"col-form-label\">종료 날짜</label> <input type=\"date\" class=\"form-control\" id=\"calendar_end_date\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-warning\" data-dismiss=\"modal\" id=\"addCalendar\">등록</button>\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\" id=\"sprintSettingModalClose\">취소</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- 일지모달 end -->\n");
      out.write("\n");
      out.write("		<!-- Main End -->\n");
      out.write("\n");
      out.write("		<!-- / Layout page -->\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- Overlay -->\n");
      out.write("	<div class=\"layout-overlay layout-menu-toggle\"></div>\n");
      out.write("	</div>\n");
      out.write("	<!-- / Layout wrapper -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- head_link 2 -->\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Core JS -->\r\n");
      out.write("    <!-- build:js assets/vendor/js/core.js -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/jquery/jquery.js\"></script>\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/popper/popper.js\"></script>\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/js/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/js/menu.js\"></script>\r\n");
      out.write("    <!-- endbuild -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendors JS -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/vendor/libs/apex-charts/apexcharts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main JS -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page JS -->\r\n");
      out.write("    <script src=\"/resources/sneat/assets/js/dashboards-analytics.js\"></script>");
      out.write("\n");
      out.write("	<!-- head_link 2  End -->\n");
      out.write("	\n");
      out.write("	<script src=\"/resources/js/calendar.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("		//날짜데이터에 언제든 접근하기 위해 현재 날짜들을 배열에 담아놓는다 \n");
      out.write("		let dayBoxList = [];\n");
      out.write("		\n");
      out.write("		//휴무를 담을 배열\n");
      out.write("		let holidayBox =[];\n");
      out.write("\n");
      out.write("		function getHolidayList(){\n");
      out.write("			$.ajax({\n");
      out.write("				url:\"/rest/holiday\",\n");
      out.write("				method:\"get\",\n");
      out.write("				success:function(result,status,xhr){\n");
      out.write("					\n");
      out.write("					console.log(result);\n");
      out.write("					console.log(dayBoxList);\n");
      out.write("					\n");
      out.write("					//DB에 들어있는 날짜와 대조해서 날짜 색칠\n");
      out.write("					for (let i = 0; i < result.length; i++) {\n");
      out.write("						let yy = result[i].yy;\n");
      out.write("						let mm = result[i].mm;\n");
      out.write("						let dd = result[i].dd;\n");
      out.write("						\n");
      out.write("						console.log(\"yy\",yy);\n");
      out.write("						console.log(\"mm\",mm);\n");
      out.write("						\n");
      out.write("						console.log(\"입력된텍스트월\",document.getElementById(\"calYear\").innerText)\n");
      out.write("						\n");
      out.write("		                //월의 날짜만큼 반복문 돌리자 \n");
      out.write("		                for (let a = 1; a <= dayBoxList.length; a++) { //1,=\n");
      out.write("		                    if (dd == a + 1) {\n");
      out.write("		                        console.log(dd, \"날은 휴가에욤\");\n");
      out.write("		                        if(dayBoxList[a].className!=\"pastDay\" && yy==document.getElementById(\"calYear\").innerText && leftPad(mm)== document.getElementById(\"calMonth\").innerText ){\n");
      out.write("			                        dayBoxList[a].classList.add(\"choiceDay\");\n");
      out.write("		                        }\n");
      out.write("		                    }\n");
      out.write("		                }\n");
      out.write("		            }\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		//날짜정보를 가진 p 태그의 DOM을 넘겨받음\n");
      out.write("		function deleteHoliday(obj){\n");
      out.write("			\n");
      out.write("			if(obj ==undefined || obj.className==\"pastDay\" || obj.className==\"futureDay\" ){\n");
      out.write("				return;\n");
      out.write("			}\n");
      out.write("			if(confirm(obj.innerText+\"날을 삭제하실래요?\")){\n");
      out.write("				 obj.classList.remove(\"choiceDay\");\n");
      out.write("				 console.log(\"nowMonth.getFullYear\",nowMonth.getFullYear());\n");
      out.write("				 console.log(\"nowMonth.getMonth\",nowMonth.getMonth()+1);\n");
      out.write("				 \n");
      out.write("				 let yy= String(nowMonth.getFullYear());\n");
      out.write("				 let mm= String(nowMonth.getMonth()+1);\n");
      out.write("				 let dd= obj.innerText;\n");
      out.write("				 \n");
      out.write("				 let day=dd.replace(/(^0+)/, \"\");\n");
      out.write("				 \n");
      out.write("				 let json={\n");
      out.write("						 yy:yy,\n");
      out.write("						 mm:mm,\n");
      out.write("						 dd:day\n");
      out.write("					 };\n");
      out.write("				 \n");
      out.write("				 console.log(\"json은?\",json);\n");
      out.write("				 \n");
      out.write("				 $.ajax({\n");
      out.write("					 url:\"/rest/holiday\",\n");
      out.write("					 method:\"delete\",\n");
      out.write("					 dataType:\"json\",\n");
      out.write("					 contentType:\"application/json\",\n");
      out.write("					 data:JSON.stringify(json),\n");
      out.write("					 success:function(result, status, xhr){\n");
      out.write("						 \n");
      out.write("					 }\n");
      out.write("				 });\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("        //onload\n");
      out.write("        $(function () {\n");
      out.write("        	getHolidayList();\n");
      out.write("        	limitDate();\n");
      out.write("            buildCalendar();\n");
      out.write("            callModal();\n");
      out.write("            reigstModal();\n");
      out.write("            deleteHoliday();\n");
      out.write("            \n");
      out.write("            $(\"#bt_go\").click(function(){	\n");
      out.write("            	\n");
      out.write("            	if(confirm(\"일정을 시작하시겠습니까?\")){\n");
      out.write("	            	$(\"#pet_today\").hide();\n");
      out.write("	            	$(\"#pet_showlist\").hide();\n");
      out.write("	            	$(\"#pet_live\").show();\n");
      out.write("            	}\n");
      out.write("            	\n");
      out.write("            	$(\"#bt_go\").attr(\"disabled\",true);\n");
      out.write("            	\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            $(\"#bt_res\").click(function(){\n");
      out.write("            	$(\"#pet_today\").hide();\n");
      out.write("            	$(\"#pet_live\").hide();\n");
      out.write("            	$(\"#pet_showlist\").show();\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            $(\"#bt_today\").click(function(){\n");
      out.write("            	$(\"#pet_today\").show();\n");
      out.write("            	$(\"#pet_live\").hide();\n");
      out.write("            	$(\"#pet_showlist\").hide();\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            $(\"#bt_live\").click(function(){\n");
      out.write("            	\n");
      out.write("            	if(document.getElementById(\"bt_go\").disabled==true){\n");
      out.write("	            	$(\"#pet_today\").hide();\n");
      out.write("	            	$(\"#pet_live\").show();\n");
      out.write("	            	$(\"#pet_showlist\").hide();\n");
      out.write("            	}\n");
      out.write("            });\n");
      out.write("\n");
      out.write("\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
